var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/plaid/exchange-token/route.js")
R.c("server/chunks/node_modules_c29c2f55._.js")
R.c("server/chunks/node_modules_next_0541b7f6._.js")
R.c("server/chunks/node_modules_mime-db_f53cdd2e._.js")
R.c("server/chunks/node_modules_axios_dist_node_axios_cjs_ef84af05._.js")
R.c("server/chunks/node_modules_plaid_dist_api_da7723ba.js")
R.c("server/chunks/node_modules_plaid_dist_ad44e3e5._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_4cf9780e._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_87d9d147._.js")
R.c("server/chunks/[root-of-the-server]__d8b207e0._.js")
R.c("server/chunks/[root-of-the-server]__40886995._.js")
R.c("server/chunks/_next-internal_server_app_api_plaid_exchange-token_route_actions_e5225dd7.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/plaid/exchange-token/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/plaid/exchange-token/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
